name: mydumper Build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make build
